apiVersion: v1
kind: Namespace
metadata:
  name: xgo-test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: xgo-test
spec:
  serviceName: "nginx-headless"  # Required for stable DNS (see headless service below)
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
# Removed headless service
# Optional standard ClusterIP service for access
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: xgo-test
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
